version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.1
    ports:
      - '12201:12201'
      - '9600:9600'
    volumes:
      - /opt/logstash/config/:/usr/share/logstash/config/
      - /opt/logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - backend
    restart: unless-stopped
