version: '3'
services:
  elasticsearch:
    command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    environment:
      cluster.name: "docker-cluster"
      bootstrap.memory_lock: "false"
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
    ulimits:
      memlock: 
        soft: -1
        hard: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - backend
  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.1
    ports:
      - '12201:12201'
    volumes:
      - /opt/logstash/config/:/usr/share/logstash/config/
      - /opt/logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - backend
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.0
    ports:
      - "5601:5601"
    networks:
      - backend
  nginx:
    image: 'nginx:1'
    ports:
        - '9200:9200'
    networks:
        - backend
    command: |
      /bin/bash -c "echo '
      server {
        listen 9200;
        add_header X-Frame-Options "SAMEORIGIN";
        location / {
            proxy_pass http://elasticsearch:9200;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
      }' | tee /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
volumes:
  esdata:
    driver: local
networks:
  backend:
    driver: overlay
